#!/bin/sh

lynxpath=/usr/local/bin/lynx

if [ -e "$HOME/.lynx/lynx/lynx.cfg" ];then
  export LYNX_CFG="$HOME/.lynx/lynx/lynx.cfg"
fi

if [ -e "$HOME/.lynx/lynx/lynx.lss" ];then
  export LYNX_LSS="$HOME/.lynx/lynx/lynx.lss"
fi

if [ ! -x "$lynxpath" ]; then
  echo "Doesn't look like lynx is installed."
  exit 1
fi

exec "$lynxpath" "$@"